# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

matrix:
  include:
    - osx_image: xcode10.3
      language: swift
      env: TEST_DEVICE='platform=iOS Simulator,OS=12.3,name=iPhone SE'

# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
  - >
    set -o pipefail && xcodebuild test -enableCodeCoverage YES 
    -workspace Example/ApolloAlamofire.xcworkspace -scheme Example
    -sdk iphonesimulator -destination "$TEST_DEVICE" | xcpretty
  - pod repo update
  - pod lib lint --allow-warnings
